### ISSUE TITLE
Didn't change the `dependencyManagement` verison

### ISSUE THREAD

**Issue by qrqhuang** [Felixzz/maven-project-version-plugin#6]
In parent pom. We always limit the child version with `dependencyManagement`

### parent.pom.

```
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.github.qrqhuang</groupId>
                <artifactId>module-a</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>com.github.qrqhuang</groupId>
                <artifactId>module-b</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

### mobule-b.pom 
no need to limit the version.

```
    <dependencies>
        <dependency>
            <groupId>com.github.qrqhuang</groupId>
            <artifactId>module-a</artifactId>
        </dependency>
    </dependencies>
```

###
After plugin invoke, the `dependencyManagement` version still the old, that's not expected. 
If you use `version:set`， it should be updated together.

**Comment by Felixzz** [comment]
Roger that. I'll fix it in the next version

**Comment by Felixzz** [comment]
I have submitted the latest version 
It’s pending JetBrains' approval, so reopen it

**Comment by Felixzz** [comment]
@qrqhuang Version 1.0.7 of the Maven Project Version plugin has been approved by JetBrains and is now publicly available by the [link](https://plugins.jetbrains.com/plugin/14904-maven-project-version/versions/stable/102361).

**Comment by Felixzz** [comment]
@qrqhuang Should you have any questions or comments, feel free to send them to me
